### ISSUE TITLE
KITIT dataset

### ISSUE THREAD

**Issue by yanyiquan** [jwchoi384/Gaussian_YOLOv3#1]
Can you provide model/cfg file/evaluate code for KITIT dataset used in your paper ?

**Comment by jwchoi384** [comment]
@Quanbnh
Hi, I uploaded .cfg, .data, and .names files for KITTI used in our paper.
Also, i added some functions in "example/detector.c" for kitti print out.
For KITTI evaluation, please see this site (http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=2d).
You can download the KITTI evaluation code. 

Unfortunately, the hard drive where the KITTI model is stored has failed...
I'm looking for a backup file, but I haven't found it yet.
However, if you use the code we provided, you can reproduce our results.
Give it a try.

**Comment by CuongNguyen218** [comment]
@jwchoi384 
Hi, I want to set IOU thresh_hold is 0.75 for car and 0,5 for the others like your paper. How should i do to archive that ?

**Comment by jwchoi384** [comment]
@CuongNguyen218 
Hi, you can set IOU threshold in evaluation code.
I uploaded BDD evaluation code ("bdd_evaluation/evaluate.py") in my repo.
If you want to evaluate KITTI dataset, please visit to the below link and download the evaluation code.
http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=2d

Anyway, we used an IOU threshold of 0.75 for all classes in the BDD data.
The IOU threshold of KITTI dataset is set to 0.7 for cars, and 0.5 for cyclist and pedestrian.
Both are default IOU threshold value for each dataset .

If you want to change the IOU threshold in BDD evaluation code, see the below code.
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/5745e3b70a6b2c005f862f0936a60aef6b2253e4/bdd_evaluation/evaluate.py#L189

**Comment by CuongNguyen218** [comment]
@jwchoi384 
Hi, I just run your code and result seem very good but i have a question: How you can eval mAP of KITTI dataset ? Use the traditional formula like others object detection papers because  I don't see mAP when I run eval code of KITTI dataset ( just E M H AP of the class)

**Comment by jwchoi384** [comment]
@CuongNguyen218 
Hi, 
Like this paper (https://arxiv.org/abs/1612.01051), mAP is calculated as the average of the 3 difficulty levels (easy, medium, hard) of 3 categories (car, cyclist, pedestrian).
