### ISSUE TITLE
train myown data?

### ISSUE THREAD

**Issue by henbucuoshanghai** [jwchoi384/Gaussian_YOLOv3#10]
my data is voc2007 format?how to train it

**Comment by qiumei1101** [comment]
how to test my video?Thanks

**Comment by jwchoi384** [comment]
@henbucuoshanghai 
You need to convert format.
Please read this post (https://pjreddie.com/darknet/yolo/).

**Comment by qiumei1101** [comment]
Hi, could you please share a demo to test video in real time?
