### ISSUE TITLE
How to prepare bdd dataset for training?

### ISSUE THREAD

**Issue by MasonForFun** [jwchoi384/Gaussian_YOLOv3#13]
Hi jwchoi384,
Thanks for the awsome project. I wonder how to prepare the dataset for training. Except I need to generate test_bdd_list.txt, train_bdd_list.txt and val_bdd_list.txt, do I need to generate a label txt file for each image? And should the label txt file be in the same folder with responding image?

Finally, is there a script to reference?

**Comment by jwchoi384** [comment]
@MasonForFun 
Yes, you need to generate a label txt file for each image. It is sames as YOLOv3.
And, the label txt file should be in the same folder with image.

I uplaoded the file (json to txt, "bdd_json2txt") in "bdd_evaluation" directory.
I think you can use the file to convert json to txt for training.

1. Setup the mypath in "bdd_json2txt.py" as directory that contains bdd json file. 
2. Setup the outpath "bdd_json2txt.py" as directory that plan to save txt file. 
3. python bdd_json2txt.py

**Comment by MasonForFun** [comment]
@jwchoi384 
Thanks for the reply. I test the bdd_json2txt.py, the error output is following
FileNotFoundError: [Errno 2] No such file or directory: '/media/disk2/dataset/bdd100k/images/bdd100k_images_images_val.jpg'

I use bdd100k_labels_release.zip to get json files, which includes the following json files.
bdd100k_labels_images_train.json
bdd100k_labels_images_val.json

Do I get the right json files?

**Comment by jwchoi384** [comment]
@MasonForFun 
I used old format, and it is updated after 08-28-2018.
(https://github.com/ucbdrive/bdd-data/blob/master/doc/format.md)
The files you said are the latest files. (yes, It is right files)
So, you need to modify the code ("bdd_json2txt").

**Comment by MasonForFun** [comment]
@jwchoi384 
Ok. I will modify bdd_json2txt according to the new format.
Thanks for the advice.
