### ISSUE TITLE
FP from a false localization can lead fatal accidents?

### ISSUE THREAD

**Issue by andeyeluguo** [jwchoi384/Gaussian_YOLOv3#15]
I don't think the low FP will lead a accident. because when the  car with the ADAS system detects a obstacle that does not really exists,  it will stop. I think the high FN will lead to the accident.

**Comment by jwchoi384** [comment]
@andeyeluguo 
In autonomous driving, the cause of the accident can be divided into two categories.
The first is true positive, and the second is false positive. Both can lead to fatal accident.
If the model misses the true positive, a car can hit a road object or person. If the model outputs many false positives, it causes excessive reactions such as unexpected braking.
So, If a car that runs fast on the highway stops suddenly, it can crash into the behind car and cause a wreck.
https://www.wired.com/story/self-driving-cars-uber-crash-false-positive-negative/
