### ISSUE TITLE
how do you think about NLL loss?

### ISSUE THREAD

**Issue by andeyeluguo** [jwchoi384/Gaussian_YOLOv3#17]
the Lx is negative log likelihood loss. But why the it is negative and log. May you use the log may get rid of the e of normal distribution.

**Comment by jwchoi384** [comment]
@andeyeluguo 
What's that mean?
In NLL loss function, value of log has negative or zero. 
So, a negative sign is needed in equation (5).

**Comment by andeyeluguo** [comment]
![log](https://user-images.githubusercontent.com/12607564/68101639-9a4c7000-ff09-11e9-8af7-aac6cb063ded.jpg)
the log function is like this, when the a is e, it is not negative or zero while x > 1

**Comment by andeyeluguo** [comment]
![image](https://user-images.githubusercontent.com/12607564/68101765-41310c00-ff0a-11e9-8722-03c515e59d71.png)
Oh , I know you mean when it come across the norm function, it will get -(x-u)^2/(2*delta)^2 ,that it is negtive or zero.

**Comment by andeyeluguo** [comment]
but the f(x) may be bigger than 1, although log[delta * sqrt(2*pi)*f(x)] will be smaller than 0

**Comment by jwchoi384** [comment]
@andeyeluguo 
Unfortunately, I do not understand what you are talking about exactly.
But, I think I didn't explain it properly before.
In NLL loss function, we want to minimize the loss. So, minus sign and log are needed.
Please see [this link](https://stats.stackexchange.com/questions/141087/i-am-wondering-why-we-use-negative-log-likelihood-sometimes).
In addition, please see [this paper](http://papers.nips.cc/paper/7141-what-uncertainties-do-we-need-in-bayesian-deep-learning-for-computer-vision.pdf), the NLL equation and loss attenuation are explained well.

**Comment by andeyeluguo** [comment]
thank you

**Comment by andeyeluguo** [comment]
the NLL  loss like self-information
