### ISSUE TITLE
when i train my own dataset, the error "darknet: ./src/parser.c:340: parse_region: Assertion `l.outputs == params.inputs' failed." I have modified my cfg due to the paper.

### ISSUE THREAD

**Issue by Dugujiujian12321** [jwchoi384/Gaussian_YOLOv3#18]

**Comment by jwchoi384** [comment]
@Dugujiujian12321 
You should change the output filter size of [convolution layer] before [Gaussian_yolo] layer.
filters = (classes + 8 + 1) * 3 (numbers in mask).
If you have 3 classes, then the filter size is (3 + 8 + 1)*3.
