### ISSUE TITLE
Did you compare Gaussian_YOLOv3 with GIoU?

### ISSUE THREAD

**Issue by AlexeyAB** [jwchoi384/Gaussian_YOLOv3#2]
Hi, nice work!

Did you compare Gaussian_YOLOv3 with GIoU?

* https://github.com/generalized-iou/g-darknet
* https://arxiv.org/abs/1902.09630v2
* https://giou.stanford.edu/
* https://github.com/AlexeyAB/darknet/issues/3249

Or you can try to combine Gaussian_YOLOv3 + GIoU.

**Comment by jwchoi384** [comment]
@AlexeyAB 
Hi, I didn't compare Gaussian YOLOv3 with GIoU.
I'm working on another project now, so I'll try it if I can afford it.
Thanks.

**Comment by zpmmehrdad** [comment]
@ALexeyAB Hi,

Have you tried to combine Gaussian and GIoU? If yes, Could you share the result?

Thanks
