### ISSUE TITLE
Why we need w_scale?

### ISSUE THREAD

**Issue by cizhenshi** [jwchoi384/Gaussian_YOLOv3#20]
In the paper, "w_scale in equation (8) is calculated based on the width and height
ratios of the GT bbox in an image, as shown in (9). It provides different weights according to the object size during training."  
I don't understand why loss should be weighted according to the size of the objects? Thanks.

**Comment by jwchoi384** [comment]
@cizhenshi 
Hi, "Wscale" is default parameter of YOLOv3. I added it for explanation of equation (5) and (8).
It is a bias value for obtaining a higher delta of small objects, because small objects require more accurate location and size for higher mAP.
