### ISSUE TITLE
Test on my own dataset error?

### ISSUE THREAD

**Issue by kokozeng** [jwchoi384/Gaussian_YOLOv3#21]
I use eval = bdd and eval  = coco in *.data file.
Try test and valid command.
test return nothing
valid return .json file, but json file is empty.
so how to test on my own dataset train weights?

**Comment by jwchoi384** [comment]
@kokozeng 
If test and valid return nothing, It seems that the model is not trained properly.
Please check your list files, images and ground-truth file.
You must make list files of your own dataset like BDD list files in my repo.
In addition, you must modify the valid file path in *.data file for validation.
