### ISSUE TITLE
a question about equation (5)

### ISSUE THREAD

**Issue by cizhenshi** [jwchoi384/Gaussian_YOLOv3#23]
In the equation (5),  Loss function is defined as **-log(N(x|μ,σ)**. I think N(x|μ，σ）is the value of probability density function of gaussian distribution.  What does that mean? Does it reflect the probability?

**Comment by jwchoi384** [comment]
@cizhenshi 
Hi, Please see the equation and explanation of these pages. [[link1](http://jrmeyer.github.io/machinelearning/2017/08/18/mle.html)], [[link2](https://math.stackexchange.com/questions/2853070/prove-neg-log-likelihood-for-gaussian-distribution-is-convex-in-mean-and-varian)], [[link3](https://stats.stackexchange.com/questions/141087/why-do-we-minimize-the-negative-likelihood-if-it-is-equivalent-to-maximization-o)].
Our model predicts the distribution.

**Comment by cizhenshi** [comment]
Thank you very much!!!!!
