### ISSUE TITLE
Support yolov2?

### ISSUE THREAD

**Issue by PyNancy** [jwchoi384/Gaussian_YOLOv3#24]
hi ，i try to train yolov2 by your code(Gaussian), but report error“Floating point exception (core dumped)”

**Comment by jwchoi384** [comment]
@PyNancy 
Hi, It only work on YOLOv3, because YOLOv2 uses "region_layer" not "yolo_layer".
So, If you want to apply our proposed method on YOLOv2, you must modify the "region_layer.c".

**Comment by PyNancy** [comment]
ok，thanks very much， i will try
