### ISSUE TITLE
Is there a report on COCO?

### ISSUE THREAD

**Issue by KaiOtter** [jwchoi384/Gaussian_YOLOv3#25]
Maybe, the motivation of authors at beginning is to optimize YOLOv3's behavior on autonomous driving dataset. Well, if the explanation of Gaussian and location score is true, it seems workable for general object detection. So. I'm very curious about the mAP result of COCO. 

If training from ImageNet pretrained model are expensive, I hope anyone can offer a result of fineture reult on a well-trained YOLOv3 model witch implement the modification proposed in this paper.

**Comment by jwchoi384** [comment]
@KaiOtter 
Hi, The mAP of COCO is mentioned in our [[paper](http://openaccess.thecvf.com/content_ICCV_2019/html/Choi_Gaussian_YOLOv3_An_Accurate_and_Fast_Object_Detector_Using_Localization_ICCV_2019_paper.html)].

**Comment by AlexeyAB** [comment]
@jwchoi384 Hi,
Can you share `yolov3_gaussian_COCO.weights` for COCO?

**Comment by jwchoi384** [comment]
@AlexeyAB 
Hi, the hard drive where our model weights are stored has failed...
I can't find a backup file, so, it's hard to provide weight file right now. 
When I have time later, I will try to reproduce it.
