### ISSUE TITLE
How to KITTI evaluation code

### ISSUE THREAD

**Issue by linchunmian** [jwchoi384/Gaussian_YOLOv3#28]
Hi, could you please teach me to use KITTI evaluation code? Now, I have trained my model and obtained predicted results on test data based on trained model. And then the evaluation code have been downloaded from the official website. But I  cannot use it, and how can I do next? Please help me to continue!
Thanks in advance!

**Comment by jwchoi384** [comment]
@ChunmianLin 
It is difficult to explain how to use the KITTI evaluation code in writing. I think you can do it, if you see the code carefully.
