### ISSUE TITLE
python/darknet.py

### ISSUE THREAD

**Issue by lijain** [jwchoi384/Gaussian_YOLOv3#29]
I want to ask about Python / darknet.py  res.append([meta.names[i], dets[j].prob[i], [b.x, b.y, b.w, b.h]])
When output, when J > 1, error is always reported? It seems that there is no such value

**Comment by jwchoi384** [comment]
@lijain 
Hi, i didn't use it. I imported this file from the original YOLOv3 repository.
You can ask this code here: https://github.com/pjreddie/darknet
