### ISSUE TITLE
Questions about confidence score threshold

### ISSUE THREAD

**Issue by xuannianz** [jwchoi384/Gaussian_YOLOv3#30]
Hi, @jwchoi384. Thanks for this wonderful project.
Since I did not find any confidence score threshold in the bdd evaluation script, I wonder if you set confidence score threshold when evaluate.

If the answer is yes, how do you set the thresholds when you evaluate YOLOv3 and Gaussian_YOLOv3? After multiply the box certainty score, the final confidence score in Gaussian_YOLOv3 would be a little smaller than the one in YOLOv3.

**Comment by jwchoi384** [comment]
@xuannianz 
Hi, I did experiment using both threshold (th=0.005 and th=0.001).
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/7b853ca4e76d18dc244b78a772d88f0425ba0698/examples/detector.c#L537

https://github.com/jwchoi384/Gaussian_YOLOv3/blob/7b853ca4e76d18dc244b78a772d88f0425ba0698/examples/detector.c#L634

Both values are default validation threshold in original YOLOv3 implementation.
In my paper, I posted mAP results of BDD and KITTI dataset using th=0.001.

**Comment by xuannianz** [comment]
Got it, thanks.
