### ISSUE TITLE
Adapting this to the other yolo-based networks

### ISSUE THREAD

**Issue by canyilmaz90** [jwchoi384/Gaussian_YOLOv3#31]
Can we adapt this approach to the other networks -like tiny yolo- by changing yolo layer to the gaussian yolo layer and adjusting filter size?

**Comment by jwchoi384** [comment]
@canyilmaz90 
Hi, you can adapt this approach to tiny YOLOv3. I've done it before.
As you know, you must change the filter size and yolo layer to Gaussian yolo layer.

**Comment by canyilmaz90** [comment]
@jwchoi384 thanks a lot :)
