### ISSUE TITLE
bdd100k server

### ISSUE THREAD

**Issue by linchunmian** [jwchoi384/Gaussian_YOLOv3#33]
Hi, I delivered the predicted result on test data to the BDD100K server, but I don't receive any response yet. And I sent the email to the official, there was also no any information returned to me. Do you know what's the problem? Is Does the server exist some bugs? How do you receive your test result?
Please help me! Thanks!

**Comment by jwchoi384** [comment]
@ChunmianLin 
Hi, I often had the same problem.
In my opinion, if the size of the evaluation file is large, the BDD server sometimes does not evaluate it.
Often, if not evaluated, I uploaded the detection result separately for each class.
And mAP was calculated by averaging each AP.

**Comment by linchunmian** [comment]
Thanks. But how to upload the detection result of each class? And how does the server calculate the mAP of each class? Could you please say it in detail.
Thanks a lot!

**Comment by jwchoi384** [comment]
@ChunmianLin 
Please modify the below code in `print_bdd_detections()` in `detector.c`.
```javascript
for(j = 0; j < classes; ++j)
{
    if (dets[i].prob[j])
    {
      fprintf(fp, "\t{\n\t\t\"name\":\"%s\",\n\t\t\"category\":\"%s\",\n\t\t\"bbox\":[%f, %f, %f, %f],\n\t\t\"score\":%f\n\t},\n", image_path, bdd_ids[j], bx1, by1, bx2, by2, dets[i].prob[j]);
     }
}
```
And, upload the result file of each class in BDD evaluation server.

For example, If you want to print first category result, please add `if(j==0)` in above code.
And then, upload the result file of first category to BDD server.
After uploading, you can see the result of each class in BDD server.
In this case, we only know the AP of each class. You must calculate the mAP using AP result. (just average of APs)

**Comment by linchunmian** [comment]
Thanks very much.@jwchoi384
And I am going to try it again. What I confuses now is that, when I upload single-class test result, would the server  only output the mAP of corresponding class? So amazing and smart!

**Comment by linchunmian** [comment]
Hi, jwchoi384. If I want to test FPS, how need I do? How the mainstream method does?

**Comment by linchunmian** [comment]
And FLOPs, how to get it?
Please help me. Thanks!

**Comment by jwchoi384** [comment]
@ChunmianLin 
If you run validation, you can see the FPS result in your screen.
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/7d2ab7c927414f912a647c93ce807fbfb448255e/examples/detector.c#L614

FLOPs is calculated by your hand. Or please see the screen when it start run. You can see the layer type, filter size, input size, output size, and FLOPs information.

**Comment by linchunmian** [comment]
Hi, jwchoi384. Last time you taught me to generate test resut of each class and submit to the server. 
I tried to calcualte mAP result of validation data by using the whole classes and single class each time, but I found the result that obtained from these two method was quite different. For example, when I used all val data, the mAP of car was 43.08%; but if I only calculated this class, the mAP was quite low, maybe 10.1%. I don’t know what is the problem? Therefore, I don’t have using single-class method for test data due to the error result.
Do you have some advice for me?

Sincerely.

发送自 Windows 10 版邮件应用

发件人: Jiwoong Choi
发送时间: 2019年11月20日 12:18
收件人: jwchoi384/Gaussian_YOLOv3
抄送: ChunmianLin; Mention
主题: Re: [jwchoi384/Gaussian_YOLOv3] bdd100k server (#33)

@ChunmianLin
If you run validation, you can see the FPS result in your screen.
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/7d2ab7c927414f912a647c93ce807fbfb448255e/examples/detector.c#L614
FLOPs is calculated by your hand. Or please see the screen when it start run. You can see the layer type, filter size, input size, output size, and FLOPs information.

**Comment by linchunmian** [comment]
Thanks. 
Acutually, I don’t use your code because I don’t have the basis of C language. I am attempting to reproduce your model and result, but I don’t know how to test the model flops and FPS. Also, due to the C evaluation code, I still stuck in KITTI evaluation. So in your opinion, how should I do next in current case.

Very thanks fro your helps in this period of time.

Sincerely.

发送自 Windows 10 版邮件应用

发件人: Jiwoong Choi
发送时间: 2019年11月20日 12:18
收件人: jwchoi384/Gaussian_YOLOv3
抄送: ChunmianLin; Mention
主题: Re: [jwchoi384/Gaussian_YOLOv3] bdd100k server (#33)

@ChunmianLin
If you run validation, you can see the FPS result in your screen.
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/7d2ab7c927414f912a647c93ce807fbfb448255e/examples/detector.c#L614
FLOPs is calculated by your hand. Or please see the screen when it start run. You can see the layer type, filter size, input size, output size, and FLOPs information.
