### ISSUE TITLE
Training result is not convergent

### ISSUE THREAD

**Issue by Sylvia-Vee** [jwchoi384/Gaussian_YOLOv3#34]
Hi, jwchoi

when I training Gaussian yolov3 model (lr = 0.0001   0.00001 0.000001),  the avg loss value can't converge, after the loss value touched 1, then the loss start increase slowly.

have you met this problem, did I missed some details?

**Comment by jwchoi384** [comment]
@zhangchenxia 
Hi,
In training, please check the mAP rather than loss value. Loss value is just the value related to delta.
Please see the below comment.
https://github.com/jwchoi384/Gaussian_YOLOv3/issues/19#issuecomment-553878638

**Comment by Sylvia-Vee** [comment]
Hi, Jwchoi
      I re-trained the model as you said, more attention about mean variances  delta values  variance values, the variance value converged to 0.2  0.11  0.09  0.1, then I tested in valid data set, the mAP still far away from our original mAP,  I can't figure out the issue's point, is this suitable for little object detection(about 9~30 pixel)?

**Comment by jwchoi384** [comment]
@zhangchenxia 
Did you use the bdd or KITTI datasets?
What is your cfg file?
How long did you train?
What's your detection threshold in evaluation?
What is your original mAP? is it YOLOv3?
As shown in our paper, it is suitable any size of object, because we apply the methods in each detection layer.

**Comment by Sylvia-Vee** [comment]
yes, our original model is trained with yolo v3 mAP: 91.76  class: 2 lr = 0.001  Gaussian mAP:48.11
trained about 3 days with 5 gpus about 100000 batch ( 32  16)
the evaluation threshold is same as before: 0.5
cfg: I used BDD.cfg, changed some parameters 
I don't know why,  the detection rate in batch 45000 is about 3500, in 97000 is about 2600 (total about 4500)

**Comment by jwchoi384** [comment]
@zhangchenxia 
The evaluation threshold I used was 0.005.
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/b3c0ec2c10337f563ee115708760553a87626b70/examples/detector.c#L537

For calculating mAP, we usually set small confidence threshold.
Please see the below link.
https://github.com/rafaelpadilla/Object-Detection-Metrics

In addition, the lr is 0.0001
After multiply the box certainty score, the final confidence score in Gaussian_YOLOv3 would be a little smaller than the one in YOLOv3.
Please try again using the threshold mentioned above.

**Comment by xwshan** [comment]
> Hi, jwchoi
> 
> when I training Gaussian yolov3 model (lr = 0.0001 0.00001 0.000001), the avg loss value can't converge, after the loss value touched 1, then the loss start increase slowly.
> 
> have you met this problem, did I missed some details?

矮墩墩你好，想问一下你在训练Gaussian yolov3 model时候，loss需要多久降低到100以下。我在训练的时候loss降低不下来，所以想请教一下你。

**Comment by Sylvia-Vee** [comment]
> > Hi, jwchoi
> > when I training Gaussian yolov3 model (lr = 0.0001 0.00001 0.000001), the avg loss value can't converge, after the loss value touched 1, then the loss start increase slowly.
> > have you met this problem, did I missed some details?
> 
> 矮墩墩你好，想问一下你在训练Gaussian yolov3 model时候，loss需要多久降低到100以下。我在训练的时候loss降低不下来，所以想请教一下你。

我是做二分类的小物体检测，降到100之下，单卡大约在4000batch之后
