### ISSUE TITLE
Model validation

### ISSUE THREAD

**Issue by milliema** [jwchoi384/Gaussian_YOLOv3#36]
Thanks for the work! I trained the Gaussian Yolov3 on my own dataset. When I tried to validate the model by using: ./darknet detector valid cfg/xx.data cfg/xx.cfg backup/xxx.weights I found all the results are saved in the /results directory with separate txt files corresponding to different categories, which may be related to "eval = xx" in cfg file. May I know what are the choices for eval? And which one is suggested for the evaluation of darknet format labels?

**Comment by jwchoi384** [comment]
@milliema 
Hi, the output file for evaluation depends on the dataset.
First of all, you need to identify the evaluation code of the dataset you want to evaluate.
And you have to write the output code accordingly.
In this repo, I provide KITTI and BDD evaluation outputs.
