### ISSUE TITLE
Why can it reduce FP?

### ISSUE THREAD

**Issue by rimu123** [jwchoi384/Gaussian_YOLOv3#38]
@jwchoi384 
Thank you for your work done.
I don't quite understand why the uncertainty of regression can reduce FP.
`float prob = objectness*predictions[class_index]*(1.0-uc_aver);`
That only reduces the prob. Can you give me some explanation?Thank you!

**Comment by jwchoi384** [comment]
@rimu123 
Through using uncertainty in prob calculation step (before NMS), the candidate which has higher confidence of three factor (bbox, objectness, and classes) is selected.
So, some candidates, which have high uncertainty of bbox, is filtered before NMS process. Thus the FP can be reduced.
As you mentioned, it can reduce the prob score, but If you think from the whole point of view, the fp is decreased, and then mAP is increased.
Please see this [[link](https://github.com/rafaelpadilla/Object-Detection-Metrics)].
