### ISSUE TITLE
why I use camera ,the process time is too long 

### ISSUE THREAD

**Issue by brucelee78** [jwchoi384/Gaussian_YOLOv3#4]
halo,thank you to open your code!
when I was get this code, I used the USB camera, and run below command:
`./darknet detector demo cfg/BDD.data cfg/Gaussian_yolov3_BDD.cfg Gaussian_yolov3_BDD.weights
`
even the teminal display the FPS is 51
but in fact,the windows of image out show is too slow, process time is too long  compared with the original YOLOV3,
so I want to know how to get better that use USB camera

and my computer's GPU is TITAN xp, i use cuda10.1
 thank you!!

**Comment by jwchoi384** [comment]
@brucelee78 
Hi, we did not modify demo.c. This is the same as the original YOLOv3 code.
Anyway, If you run the code on the server computer and display the results on your personal desktop, a network throughput problem can cause latency.
If not, try reducing the display window size.
