### ISSUE TITLE
BDD test server

### ISSUE THREAD

**Issue by linchunmian** [jwchoi384/Gaussian_YOLOv3#41]
Hi, jwchoi284. I tried to upload test result of single class to the server fro evaluation as you said before, but still no any result could be returned. I am really helpless, and do you have some ideas for me? 
Thanks in advance!

**Comment by jwchoi384** [comment]
@ChunmianLin 
Did you upload the zip file on BDD evaluation server?
The result is as shown below. (It is just the result for testing)
 ![image](https://user-images.githubusercontent.com/56669525/69737270-75999000-1177-11ea-9550-9d6453ea9ed0.png)
Please show me a screenshot.

**Comment by linchunmian** [comment]
I don't. I just upload single-class json file to the server. You mean I need package all single-class json into a zip file, and then upload?

**Comment by jwchoi384** [comment]
@ChunmianLin 
You must make a single-class json into a zip file, and then upload.
Or all-class json (not package all single-class json) into a zip file. Try it.

**Comment by linchunmian** [comment]
Thanks. I try it later.
