### ISSUE TITLE
Error with compiling a code

### ISSUE THREAD

**Issue by VladBlat** [jwchoi384/Gaussian_YOLOv3#43]
### Hello, i'm want to test this model on my data. After i cloned a files i tried to make it. And i have this error msg:
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
In file included from ./src/utils.h:5:0,
                 from ./src/gemm.c:2:
include/darknet.h:14:14: fatal error: curand.h: No such file or directory
     #include "curand.h"
              ^~~~~~~~~~
compilation terminated.
Makefile:89: recipe for target 'obj/gemm.o' failed
make: *** [obj/gemm.o] Error 1
### But darknet YOLOv3 compiles without this errors. Should paths of this project and darknet have some special structure?

**Comment by jwchoi384** [comment]
@VladBlat 
Hi, Please set `opencv = 0` in the makefile and make it.
Or, please install the opencv.
It looks like there is no opencv package.
