### ISSUE TITLE
class ordering

### ISSUE THREAD

**Issue by linchunmian** [jwchoi384/Gaussian_YOLOv3#44]
Hi, a strange idea happens to me: the test result on server doesn't give the class name corresponding to mAP value, so how can I know which value belongs to its class? And further, when I make txt training file, could  the ordering of class name be consistent with that of official test?
Thanks in advance!

**Comment by jwchoi384** [comment]
@ChunmianLin 
Please check the order in "/data/bdd.names".
You don't need to make the ordering of class name consistently in training file.

**Comment by linchunmian** [comment]
HI, I want to know how to find your kmeans clustering code in your repository? Thanks!

**Comment by jwchoi384** [comment]
Please check this [repo](https://github.com/AlexeyAB/darknet).
He explained the method to calculate the anchors in README.

**Comment by linchunmian** [comment]
Thanks. More importantly, I found the detection result of yolov3 cannot be reproduced in your code. My 512×512 evaluation result just reached 11.8%, I don’t know where the problem is. Maybe you could help me?
Thanks a lot.
 

发送自 Windows 10 版邮件应用

发件人: Jiwoong Choi
发送时间: 2019年12月17日 16:23
收件人: jwchoi384/Gaussian_YOLOv3
抄送: ChunmianLin; Mention
主题: Re: [jwchoi384/Gaussian_YOLOv3] class ordering (#44)

@ChunmianLin
Please check the order in "/data/bdd.names".
You don't need to make the ordering of class name consistently in training file.
