### ISSUE TITLE
count FP/TP

### ISSUE THREAD

**Issue by CuongNguyen218** [jwchoi384/Gaussian_YOLOv3#48]
Hi @jwchoi384 ,
I want to calculate TP/FP of KITTI dataset in your paper. How can I do it ?

**Comment by jwchoi384** [comment]
@CuongNguyen218 
I explained in detail in our paper. As mentioned our paper, we used bdd evaluation code.
When calculate TP and FP, we set detection threshold as 0.5 (test default threshold).
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/85d1d35a7044428bda60f074ca5ddddeec60c83d/examples/detector.c#L537

In addition, IoU threshold is set as official evaluation threshold value of each dataset.
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/85d1d35a7044428bda60f074ca5ddddeec60c83d/bdd_evaluation/evaluate.py#L189

**Comment by CuongNguyen218** [comment]
How about KITTI dataset ? How can I do it ?

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: Jiwoong Choi <notifications@github.com>
Đã gửi: Saturday, December 28, 2019 10:43:01 PM
Đến: jwchoi384/Gaussian_YOLOv3 <Gaussian_YOLOv3@noreply.github.com>
Cc: Nguyen Ngoc Cuong 20150510 <cuong.nn150510@sis.hust.edu.vn>; Mention <mention@noreply.github.com>
Chủ đề: Re: [jwchoi384/Gaussian_YOLOv3] count FP/TP (#48)


@CuongNguyen218<https://github.com/CuongNguyen218>
I explained in detail in our paper. As mentioned our paper, we used bdd evaluation code.
When calculate TP and FP, we set detection threshold as 0.5 (test default threshold).
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/85d1d35a7044428bda60f074ca5ddddeec60c83d/examples/detector.c#L537

In addition, IoU threshold is set as official evaluation threshold value of each dataset.
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/85d1d35a7044428bda60f074ca5ddddeec60c83d/bdd_evaluation/evaluate.py#L189

**Comment by jwchoi384** [comment]
You must print out the KITTI result as BDD format.
It is easy. Firstly, you just change `eval=kitti` to `eval=bdd` in cfg/KITTI_3cls.data.
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/85d1d35a7044428bda60f074ca5ddddeec60c83d/cfg/KITTI_3cls.data#L6

Secondly, you must change the class id as KITTI classes. (default is BDD class id)
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/5d48f43129e3012cc90b28e289ff0c4ded00860b/examples/detector.c#L74

Finally, run the BDD evaluation code using `bdd_evaluation/gt_KITTI_valid_for_bdd_eval_method.json`.
This is the ground-truth file of KITTI validation set for using BDD evaluation method.
Before running the code, you must set the IOU threshold in `bdd_evaluation/evaluate.py` mentioned above (Car is 0.7, the others are 0.5).

**Comment by CuongNguyen218** [comment]
@jwchoi384 
I should change line https://github.com/ucbdrive/bdd-data/blob/master/bdd_data/evaluate.py#L189 from `thresholds = [0.75]` to `thresholds = [0.7, 0.5, 0.5]` right?
but when i change this line it throw an error.

**Comment by CuongNguyen218** [comment]
how can i print the number of TP and FP compare to Gt box. Should I Print value of this line https://github.com/jwchoi384/Gaussian_YOLOv3/blob/master/bdd_evaluation/evaluate.py#L169, right ?
