### ISSUE TITLE
in caffe?pytorch?

### ISSUE THREAD

**Issue by henbucuoshanghai** [jwchoi384/Gaussian_YOLOv3#5]

**Comment by henbucuoshanghai** [comment]
in c++?

**Comment by jwchoi384** [comment]
@henbucuoshanghai 
I only implemented it as a C.
There is no code implemented with caffe, pytorch, and C++.

**Comment by henbucuoshanghai** [comment]
but how to train my data？

**Comment by jwchoi384** [comment]
@henbucuoshanghai 
You must make list, name, and data files.
Please read below link:
https://timebutt.github.io/static/how-to-train-yolov2-to-detect-custom-objects/
https://pjreddie.com/darknet/yolo/
