### ISSUE TITLE
Tiny yolov3 

### ISSUE THREAD

**Issue by purvikpatel** [jwchoi384/Gaussian_YOLOv3#52]
Can I use tiny yolov3 cfg file with Gaussian Yolov3? 
And if yes what changes I have to make to train images with tiny yolov3 cfg file?

**Comment by canyilmaz90** [comment]
@purvikpatel yes, you can. Clone this repo, then change layer name [yolo] to [Gaussian_yolo] in the config file and recalculate the filter numbers according to the gaussian layer. In normal yolo format, the calculation is:
`filters = (4 box coordinates + objectness score + number of classes) * number of anchor boxes`
eg. for general yolo architecture training on coco dataset (80 classes):
`filters = (4 + 1 + 80) * 3 = 255`

For gaussian yolo, the only change is the number of box coordinates, it's not 4 for gaussian yolo, but it's 8. So the calculation for the same configuration on coco dataset is:
`filters = (8 + 1 + 80) * 3 = 267`

I hope it helps :)

**Comment by jwchoi384** [comment]
@canyilmaz90 
Nice explanation!
Thanks.
