### ISSUE TITLE
Would you mind sharing your code of getting anchor size?

### ISSUE THREAD

**Issue by sisrfeng** [jwchoi384/Gaussian_YOLOv3#56]
I know the anchor size is extracted using k-means clustering for each training set of KITTI and BDD.
I want to get the anchor size on another dataset and found some k-means implement,  but I think your official implement is the best.
Would you mind sharing your code of getting anchor size?
Many thanks!

**Comment by jwchoi384** [comment]
@sisrfeng 
Hi, Please see the below link.
https://github.com/jwchoi384/Gaussian_YOLOv3/issues/44#issuecomment-568366209
