### ISSUE TITLE
mAP values 0 while evaluation

### ISSUE THREAD

**Issue by preetd14** [jwchoi384/Gaussian_YOLOv3#58]
I am trying to evaluate the bdd_results.json file which I get after running `./darknet detector valid cfg/BDD.data cfg/Gaussian_yolov3_BDD.cfg Gaussian_yolov3_BDD.weights` but it gives me 0 values for all the AP:
`here gt_bdd_val.json ../results/bdd_results.json
AP : 0.00 (bike)
AP : 0.00 (bus)
AP : 0.00 (car)
AP : 0.00 (motor)
AP : 0.00 (person)
AP : 0.00 (rider)
AP : 0.00 (traffic light)
AP : 0.00 (traffic sign)
AP : 0.00 (train)
AP : 0.00 (truck)
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] 

0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00

mAP 0.00
`

**Comment by jwchoi384** [comment]
@Preetderasari14 
Hi, 
Please run the below command.
`./darknet detector test cfg/BDD.data cfg/Gaussian_yolov3_BDD.cfg Gaussian_yolov3_BDD.weights data/example.jpg`
Do you get the results well?

If yes, please check that file names of validation output file and those in `gt_bdd_val.json`.

**Comment by preetd14** [comment]
Hey!

I am able to detect the objects without any issues and 

`./darknet detector test cfg/BDD.data cfg/Gaussian_yolov3_BDD.cfg Gaussian_yolov3_BDD.weights data/example.jpg`
gives the proper result.

I also checked the `gt_bdd_val.json` file and the file names match to that in the validation output file.
The window on the left shows the output file `gt_bdd_val.json` and the window on the right shows the `bdd_results.json` file. You can see that the image `beced1e4-8d82da4e` is present in both. So I can hypothesize that it does validate on the correct validation set.
<img width="2263" alt="Screen Shot 2020-02-12 at 7 08 24 PM" src="https://user-images.githubusercontent.com/26147230/74389101-2ef92080-4dcb-11ea-8a23-b065542f03e8.png">

But I still get 0 values during evaluation.
<img width="1133" alt="Screen Shot 2020-02-12 at 7 12 43 PM" src="https://user-images.githubusercontent.com/26147230/74389272-ad55c280-4dcb-11ea-81d0-5855503f6e5a.png">

**Comment by jwchoi384** [comment]
@Preetderasari14 
Hmm... I don't know the reason exactly.
In my case, the results come out right. 
Can you share your json file?

**Comment by preetd14** [comment]
Here you go:
[bdd_results.json.zip](https://github.com/jwchoi384/Gaussian_YOLOv3/files/4216295/bdd_results.json.zip)

**Comment by preetd14** [comment]
Hi!
Were you able to get mAP values using my file?

**Comment by jwchoi384** [comment]
@Preetderasari14 
I tried your one but I got 0 mAP.
I retested my code again, and the mAP came out right.
There is no problem with the code of Gaussian YOLOv3.
I uploaded my result file. Please check it.
Perhaps the name in json is different from yours. 
If the name of the validation set is the same as the name in json, no problem. 
I had modified the name for convenience.

[bdd_results.zip](https://github.com/jwchoi384/Gaussian_YOLOv3/files/4265940/bdd_results.zip)

**Comment by preetd14** [comment]
Hey @jwchoi384 I am getting 0 values with your results file too and I checked the name of the json file but its the same. I am not sure what is wrong.

**Comment by jwchoi384** [comment]
@Preetderasari14
Hi,
Unfortunately, I don't know why you get 0 values.
I've tried my repo again, but it works fine.

**Comment by preetd14** [comment]
Hey I know you have closed this issue but I am getting a new error now (I am getting an fps value now which I was not before and also a detection time).
![Screenshot from 2020-05-31 20-41-36](https://user-images.githubusercontent.com/26147230/83366770-2713bb00-a37f-11ea-9b0f-f178d75a2839.png)
Can you please help if you have any idea what it means?

**Comment by wangzizhe** [comment]
> Hey I know you have closed this issue but I am getting a new error now (I am getting an fps value now which I was not before and also a detection time).
> ![Screenshot from 2020-05-31 20-41-36](https://user-images.githubusercontent.com/26147230/83366770-2713bb00-a37f-11ea-9b0f-f178d75a2839.png)
> Can you please help if you have any idea what it means?

Hi Preet,

I'm having the same issue. Did you solve it now?
