### ISSUE TITLE
anchors question

### ISSUE THREAD

**Issue by 147906825** [jwchoi384/Gaussian_YOLOv3#59]
Hello, I downloaded your source code. Please ask me what statement to execute in the Darknet version if you want to cluster again? Thank you!

I tried to execute the following recalculate clustering statement, but no information was returned and no error was prompted

./darknet detector calc_anchors cfg/PIGMENT_001.data -num_of_clusters 9 -width 608 -height 608

**Comment by jwchoi384** [comment]
@147906825 
Hi, My code doesn't support that command.
Please see the link below.
https://github.com/AlexeyAB/darknet

**Comment by 147906825** [comment]
Hi, ask God your code, how to use clustering? Thank you!

**Comment by jwchoi384** [comment]
@147906825 
If you search clustering in below link, you can find the method how to use it.
https://github.com/AlexeyAB/darknet
