### ISSUE TITLE
what is your iou when you test the bdd100k？

### ISSUE THREAD

**Issue by andeyeluguo** [jwchoi384/Gaussian_YOLOv3#6]
I got 0.47map when the IOU is 0.5, I am wondering if your result is correct or not.

**Comment by jwchoi384** [comment]
@andeyeluguo 
Hi, Do you mean IOU threshold value for BDD evaluation?
As mentioned our paper, we used an IOU threshold of 0.75 for all classes in the BDD data.
This is the default IOU threshold value for BDD dataset.
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/0d672ccefccee742d9762e733a753fe7f25673d5/bdd_evaluation/evaluate.py#L189
Did you try the instruction in README.md for evaluation?
If you follow the instructions, you will get the same result.

**Comment by andeyeluguo** [comment]
yeah, you are right, when iou is 0.5 ,it is higher. thank you.
