### ISSUE TITLE
Loss value is going to be negative....How can I think this is proper convergence?

### ISSUE THREAD

**Issue by juno-ai** [jwchoi384/Gaussian_YOLOv3#60]
Negative Log-Likelihood loss value is going to be negative...
I think it's possible but....i can't make sure that the loss is converged...
Have you experienced this problem?

loss가 음수로 떨어지는데, 적정 수렴점이 어딘지 찾기가 쉽지 않습니다.
혹시 실험하시면서 이런 경험이 있으셨는지, 
있으셨다면 이런 경우 많은 실험을 통해 적정수렴점을 찾아야하는건지 궁금합니다.

**Comment by jwchoi384** [comment]
@juno-ai 
Hi, 
It is hard to find the converged point so, I calculated the accuracy per some iteration.
I recommend calculating accuracy for each weight and finding the best weight.
In addition, I think it is possible to have negative value, but I implemented our loss function like below to prevent negative loss value. (adding constant value in our loss)
https://github.com/jwchoi384/Gaussian_YOLOv3/issues/19#issuecomment-554746055
The loss varies depending on the data you use, try changing the constant value in our loss.
