### ISSUE TITLE
While mentioning fps, does the time including preprocessing?

### ISSUE THREAD

**Issue by sisrfeng** [jwchoi384/Gaussian_YOLOv3#61]
Hi, using pytorch gaussian yolov3, the Inference speed is10 fps on Tesla M60, image size=1600x1200.
Testing on the 416x416 imgs, fps=21.
So I wonder whether the time includes preprocessing while mentioning fps. 
Many thanks!

I save the resized image by adding `cv2.imgwrite('myname',img)` after `img, info_img = preprocess(img, imgsize, jitter=0) # info = (h, w, nh, nw, dx, dy)` in:

```
img = cv2.imread(image_path)
        #Preprocess image
img_raw = img.copy()[:, :, ::-1].transpose((2, 0, 1))
img, info_img = preprocess(img, imgsize, jitter=0)  # info = (h, w, nh, nw, dx, dy)
img = np.transpose(img / 255., (2, 0, 1))
img = torch.from_numpy(img).float().unsqueeze(0)

if gpu >= 0:
    # Send model to GPU
    img = Variable(img.type(torch.cuda.FloatTensor))
else:
    img = Variable(img.type(torch.FloatTensor))
```

![image](https://user-images.githubusercontent.com/53520949/77627521-021b5a00-6f82-11ea-8377-df0ae6708ff6.png)

**Comment by jwchoi384** [comment]
@sisrfeng 
Hi,
When validation, original repo and we consider image resize and inference time with multi-threading.
If you don't use multi-threading on these process, just consider only inference time.
This value (=only inference time) is almost the same as the detection time (resize+inference) when using multi-thread.
