### ISSUE TITLE
Unable to use .weights and .cfg in original Darknet repo. 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [jwchoi384/Gaussian_YOLOv3#63]
Hi,
1- I am able to use your given pre-trained models in the repo, but why I am unable to use it in original darknet repo? (https://github.com/AlexeyAB/darknet)   and in (https://github.com/erikguo/yolov3).

**Comment by jwchoi384** [comment]
@MuhammadAsadJaved 
Hi, 
Original darknet repo is https://github.com/pjreddie/darknet .
We implemented our model based on above code.
Our model has different output layer compared to original YOLOv3, so please check the cfg file.
(YOLO layer is different)
In addition, AlexeyAB repo (https://github.com/AlexeyAB/darknet) also provides Gaussian yolov3. Please check their repo instruction or cfg file.
