### ISSUE TITLE
Why no of filters not according to the formula (5+ No of classes) x 3   ? 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [jwchoi384/Gaussian_YOLOv3#64]
Hi @jwchoi384  
     In the original YOLOV3 , the no of filters in the 3 layers is according to the following formula 

(5+ no of classes) x 3

so for 10 classes it should be  (5 + 10) x 3 = 75 .    why it is 57 in Guassian_yolov3_BDD.cfg , can you explain the reason and formula? 

How I should change for different no of classes? for example for 2 classes. 

https://github.com/jwchoi384/Gaussian_YOLOv3/blob/master/cfg/Gaussian_yolov3_BDD.cfg#L604

**Comment by jwchoi384** [comment]
@MuhammadAsadJaved 
Hi,
Our output size is (C+1+4x2)xA.
C is the number of class, 1 is objectness score, and 4 is coordinate of bbox.
2 is Gaussian parameter (i.e., mu and sigma). A is the number of anchor boxes (=3)

If you use 2 classes, output size is 33 (2+1+4x2)x3.
