### ISSUE TITLE
How to show uncertainty of every bbox in result image/ video?

### ISSUE THREAD

**Issue by wangzizhe** [jwchoi384/Gaussian_YOLOv3#65]
Hi,

I would like to ask is there a way to visualize the uncertainty of every bbox in result image/ video?

Or maybe is there a way to show both the uncertainty of every bbox and probability of prediction in every bbox?

Thank you very much!

**Comment by jwchoi384** [comment]
@wangzizhe 
Hi,
I haven't tried visualize.
We stored uncertainty value in detection structure.
https://github.com/jwchoi384/Gaussian_YOLOv3/blob/18a0a7d255e28103bbfa6cbc709f0e2507c2b420/include/darknet.h#L522

https://github.com/jwchoi384/Gaussian_YOLOv3/blob/18a0a7d255e28103bbfa6cbc709f0e2507c2b420/src/gaussian_yolo_layer.c#L377

You can use that information to show uncertainty of each box.
