### ISSUE TITLE
Is there a on bdd100k trained yolov3_bdd.weights so i could analyse and compare both .weights files?

### ISSUE THREAD

**Issue by wangzizhe** [jwchoi384/Gaussian_YOLOv3#66]
Hi @jwchoi384,

do you also have your on bdd100k trained yolov3_bdd.weights file avaliable?
I would like to use the Gaussian_yolov3_BDD.weights which in the repo the the yolov3_bdd.weights to do some analyse and comparison for my study.

Thanks in advance

**Comment by jwchoi384** [comment]
@wangzizhe 
Hi, Let me know your email or send me an email (jwchoi384@gmail.com).
I will find and send it.

**Comment by wangzizhe** [comment]
@jwchoi384 
Thank you very much! I've sent you an email :)

**Comment by jwchoi384** [comment]
@wangzizhe 
Yup, I just sent you a reply.
