### ISSUE TITLE
Ask you a little question

### ISSUE THREAD

**Issue by joe660** [jwchoi384/Gaussian_YOLOv3#67]
Now that yolov4 has appeared, can your improved Gaussian loss be applied to v4? v4 already uses ciou. thanks for the reply

**Comment by jwchoi384** [comment]
Hi @joe660 ,
Probably in the repo below, adding a Gaussian YOLO layer to yolov4's cfg will work (I didn't try).
https://github.com/AlexeyAB/darknet

**Comment by joe660** [comment]
> Probably in the repo below, adding a Gaussian YOLO layer to yolov4's cfg will work (I didn't try).

Thank you for your reply. I would like to ask. The loss function of yolov4 has been changed from MES to GIOU. Does this solve the uncertain problem? Does it need to use Gaussian loss? Because I have been reading your article before, I personally find that it is not very useful on v4. I don't know what your understanding is?

**Comment by jwchoi384** [comment]
@joe660 
If I understand correctly, GIOU cannot catch bounding box uncertainty.
Conventional bounding box loss only considers the coordinates of the predicted bbox and ground-truth, so It cannot consider the noise or ambiguity (aleatoric uncetainty) of the predicted bbox.

If you only think about the accuracy, GIOU or latest other loss may be better than NLL loss on mAP.
(In our paper, I didn't compare our method with GIOU. So I don't know which one is better)
However, I think uncertainty estimation of bbox is really important in safe-critical application such as autonomous driving.
