### ISSUE TITLE
Do you have any plans for pytorch or tf implementation?

### ISSUE THREAD

**Issue by leviome** [jwchoi384/Gaussian_YOLOv3#7]
First, thanks for your great work.

**Comment by jwchoi384** [comment]
@leviome 
Hi, I only implemented it as a C.
Unfortunately, I have no plans to implement using other framework, because I'm working on another project now.
If you find YOLO implemented as a deep learning framework, you can easily model the proposed approach there.

**Comment by xuannianz** [comment]
Hi @leviome, I just implement it in keras and tensorflow. https://github.com/xuannianz/keras-GaussianYOLOv3
