### ISSUE TITLE
-nogpu lead to Incorrect detection, can you fix it?

### ISSUE THREAD

**Issue by 92ypli** [jwchoi384/Gaussian_YOLOv3#8]
![image](https://user-images.githubusercontent.com/22673185/67737218-4cd18e00-fa45-11e9-9bc1-5802ee6daeff.png)

**Comment by jwchoi384** [comment]
@92ypli 
Hi, if you want to use CPU only, please modify the value in makefile mentioned below.
`GPU=0
CUDNN=0
OPENCV=1
OPENMP=0
DEBUG=0`
And recompile it. `make`
You will get the same result as I posted.

**Comment by 92ypli** [comment]
ok, thanks you for you reply. I try it.
