### ISSUE TITLE
Training failure

### ISSUE THREAD

**Issue by Code-Fight** [jwchoi384/Gaussian_YOLOv3#9]
Hi @jwchoi384 
Thanks for you share.
I refer to your code, compiled a version, I am using your weight file and configuration file, when you reason, I can get the same result as you.
However, when I went to train myself , the network could not converge and fluctuated around 10 rounds.
Excuse me, what is the reason?
Single card, 1080ti, lr=0.001

-----------------------------------------
batch=64
subdivisions=16
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1
flip=0
learning_rate=0.001
burn_in=1000
max_batches = 50020
policy=steps
steps=40000,45000
scales=.1,.1
-----------------------------------------

Thank you very much.

**Comment by sudospike** [comment]
Single GPU is not enough, i trained yolov3 in common darknet with batchsize=48 and it failed. The used memory of GPU would change and fluctuate.It would fail when the requires is bigger than 11G

**Comment by jwchoi384** [comment]
@Code-Fight 
Hi, Please increase the subdivision value and try it again.

**Comment by Code-Fight** [comment]
Hi, @jwchoi384 
Thanks for your reply！
I will set batch=64 and subdivisions=32 ,try again
